version: 2
updates:
  - package-ecosystem: "gradle"
    directory: "/"
    open-pull-requests-limit: 0
    schedule:
      interval: "weekly"
    ignore:
      - dependency-name: "org.xhtmlrenderer:flying-saucer-core"
        versions:
          - ">=9.5.0" # requires Java 11
          #- '>=9.6.0' # requires Java 17
    groups:
      google-oauth-client:
        applies-to: "version-updates"
        patterns:
          - "com.google.oauth-client:*"
      google-http-client:
        applies-to: "version-updates"
        patterns:
          - "com.google.http-client:*"

  - package-ecosystem: "gradle"
    directory: "/buildSrc"
    open-pull-requests-limit: 0
    schedule:
      interval: "weekly"

  - package-ecosystem: "npm"
    directory: "/"
    open-pull-requests-limit: 0
    schedule:
      interval: "weekly"

  - package-ecosystem: "github-actions"
    directory: "/"
    open-pull-requests-limit: 0
    schedule:
      interval: "weekly"
